spring:
  profiles:
    active: dev
  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
        enabled: true
      datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect